sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

notifications:
  email:
    on_success: always

branches:
  except:
    - /^v[0-9]/

install:
  - pip install -r dev-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install future==0.15.2; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then pip install future==0.15.2; fi

script:
  - manage lint
  - manage test

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then exit 0; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then exit 0; fi

deploy:
  provider: pypi
  user: reubano
  password:
    secure: password

  distributions: sdist bdist_wheel
  on:
    tags: true
